CREATE TABLE articles
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL
);

CREATE TABLE labels
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  label VARCHAR NOT NULL,
  article_id INTEGER REFERENCES articles ( id ) ON DELETE CASCADE NOT NULL
);