[package]
name = "step_3_8"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = { version = "0.4.17", features = [ "std", "serde" ] }
chrono = { version = "0.4", features = [ "serde" ] }
serde = { version = "1.0.144", features = [ "derive" ] }
serde_json = "1.0.85"
